# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdf_converter/gui/pdfConverterDesign2.0.ui',
# licensing of 'pdf_converter/gui/pdfConverterDesign2.0.ui' applies.
#
# Created: Wed Aug 14 14:25:11 2019
#      by: pyside2-uic  running on PySide2 5.12.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(450, 830, 1051, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pdf_split_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/split.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pdf_split_button.setIcon(icon)
        self.pdf_split_button.setIconSize(QtCore.QSize(50, 50))
        self.pdf_split_button.setObjectName("pdf_split_button")
        self.horizontalLayout.addWidget(self.pdf_split_button)
        self.change_position_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/swap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_position_button.setIcon(icon1)
        self.change_position_button.setIconSize(QtCore.QSize(50, 50))
        self.change_position_button.setObjectName("change_position_button")
        self.horizontalLayout.addWidget(self.change_position_button)
        self.rotate_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/rotate.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotate_button.setIcon(icon2)
        self.rotate_button.setIconSize(QtCore.QSize(50, 50))
        self.rotate_button.setObjectName("rotate_button")
        self.horizontalLayout.addWidget(self.rotate_button)
        self.crop_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.crop_button.setIcon(icon3)
        self.crop_button.setIconSize(QtCore.QSize(50, 50))
        self.crop_button.setObjectName("crop_button")
        self.horizontalLayout.addWidget(self.crop_button)
        self.trash_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/trash.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trash_button.setIcon(icon4)
        self.trash_button.setIconSize(QtCore.QSize(50, 50))
        self.trash_button.setObjectName("trash_button")
        self.horizontalLayout.addWidget(self.trash_button)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(160, 190, 1591, 571))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 301, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.open_folder_button = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_folder_button.setIcon(icon5)
        self.open_folder_button.setIconSize(QtCore.QSize(50, 50))
        self.open_folder_button.setObjectName("open_folder_button")
        self.horizontalLayout_2.addWidget(self.open_folder_button)
        self.open_file_button = QtWidgets.QToolButton(self.horizontalLayoutWidget_2)
        self.open_file_button.setEnabled(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_file_button.setIcon(icon6)
        self.open_file_button.setIconSize(QtCore.QSize(50, 50))
        self.open_file_button.setObjectName("open_file_button")
        self.horizontalLayout_2.addWidget(self.open_file_button)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1790, 0, 131, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.test_button = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../icons/testing.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.test_button.setIcon(icon7)
        self.test_button.setIconSize(QtCore.QSize(50, 50))
        self.test_button.setObjectName("test_button")
        self.verticalLayout.addWidget(self.test_button)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 450, 1821, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_button = QtWidgets.QToolButton(self.horizontalLayoutWidget_3)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../icons/arrowleft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button.setIcon(icon8)
        self.left_button.setIconSize(QtCore.QSize(50, 50))
        self.left_button.setObjectName("left_button")
        self.horizontalLayout_3.addWidget(self.left_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.right_button = QtWidgets.QToolButton(self.horizontalLayoutWidget_3)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../icons/arrowright.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_button.setIcon(icon9)
        self.right_button.setIconSize(QtCore.QSize(50, 50))
        self.right_button.setObjectName("right_button")
        self.horizontalLayout_3.addWidget(self.right_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addAction(self.actionOpen_File)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pdf_split_button.setText(QtWidgets.QApplication.translate("MainWindow", "Split", None, -1))
        self.change_position_button.setText(QtWidgets.QApplication.translate("MainWindow", "swap", None, -1))
        self.rotate_button.setText(QtWidgets.QApplication.translate("MainWindow", "rotate", None, -1))
        self.crop_button.setText(QtWidgets.QApplication.translate("MainWindow", "cropping", None, -1))
        self.trash_button.setText(QtWidgets.QApplication.translate("MainWindow", "trash", None, -1))
        self.open_folder_button.setText(QtWidgets.QApplication.translate("MainWindow", "Open Folder", None, -1))
        self.open_file_button.setText(QtWidgets.QApplication.translate("MainWindow", "Open File", None, -1))
        self.test_button.setText(QtWidgets.QApplication.translate("MainWindow", "test", None, -1))
        self.left_button.setText(QtWidgets.QApplication.translate("MainWindow", "arrowleft", None, -1))
        self.right_button.setText(QtWidgets.QApplication.translate("MainWindow", "arrowright", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionOpen_Folder.setText(QtWidgets.QApplication.translate("MainWindow", "Open Folder", None, -1))
        self.actionOpen_File.setText(QtWidgets.QApplication.translate("MainWindow", "Open File", None, -1))

